Repository pwntester/octo.nvim, pull requests merged in 2024-12, with the labels that each got.

#712 Remove non-closed single quote
  lua/octo/ui/writers.lua
Labels: bug

#713 Support for ghost users
  README.md
  lua/octo/config.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/ui/bubbles.lua
  lua/octo/ui/writers.lua
Labels: bug

#716 distinguish completed from not planned
  lua/octo/commands.lua
  lua/octo/gh/graphql.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/pickers/fzf-lua/previewers.lua
  lua/octo/pickers/telescope/previewers.lua
  lua/octo/ui/colors.lua
  lua/octo/ui/writers.lua
  lua/octo/utils.lua
Labels: enhancement

#722 Support label multiselection
  lua/octo/commands.lua
  lua/octo/gh/graphql.lua
  lua/octo/pickers/fzf-lua/pickers/assigned_labels.lua
  lua/octo/pickers/fzf-lua/pickers/labels.lua
  lua/octo/pickers/telescope/provider.lua
Labels: bug, enhancement, command

#719 Specify closing reason
  lua/octo/commands.lua
  lua/octo/gh/graphql.lua
Labels: enhancement

#738 fix: add missing timeout passthrough
  lua/octo/gh/init.lua
  lua/octo/reviews/init.lua
  lua/octo/utils.lua
Labels: bug

#746 Wrapper to support parameterized queries
  lua/octo/gh/init.lua
Labels: maintenance

#753 Refactor develop command to use gh.run
  lua/octo/utils.lua
Labels: maintenance

#767 Add milestone command docs (and small modifications)
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/gh/graphql.lua
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/utils.lua
Labels: documentation
