Repository pwntester/octo.nvim, pull requests merged in 2024-10, with the labels that each got.

#632 open remote URL from any buffer w/ :Octo repo browser
  lua/octo/navigation.lua
Labels: bug, command

#630 fix the :Octo repo url command
  lua/octo/commands.lua
  lua/octo/utils.lua
Labels: bug

#636 test: fix test utils import
  lua/tests/minimal_init.vim
  lua/tests/test_utils.lua
Labels: atest

#637 Add colors based on Issue / PR state
  lua/octo/gh/graphql.lua
  lua/octo/pickers/telescope/entry_maker.lua
Labels: enhancement, telescope

#650 Keep cursor location while reloading
  lua/octo/autocmds.lua
  lua/octo/commands.lua
  lua/octo/init.lua
Labels: enhancement
