Repository pwntester/octo.nvim, pull requests merged in 2025-01, with the labels that each got.

#777 Fix buffer id error in TabClosed Autocommands
  lua/octo/reviews/file-entry.lua
Labels: bug

#773 Refactor to fragments
  lua/octo/gh/fragments.lua
  lua/octo/gh/graphql.lua
  lua/octo/gh/init.lua
Labels: maintenance

#786 fix missing event
  lua/octo/gh/graphql.lua
Labels: bug

#789 use reopenIssue to support not_planned and duplicate
  lua/octo/commands.lua
  lua/octo/gh/graphql.lua
Labels: bug

#792 735 add commit status checks to event
  lua/octo/gh/fragments.lua
  lua/octo/ui/writers.lua
  lua/octo/utils.lua
Labels: timelineItems

#793 switch ; to , in README
  README.md
Labels: documentation, maintenance

#794 add workflow to add closing labels
  .github/workflows/labels.yml
Labels: maintenance

#800 Catch stderr on pr checkout
  lua/octo/utils.lua
Labels: bug, maintenance

#803 642 abitrary selection callbacks for pickers
  lua/octo/commands.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement

#805 Add graphqlrc file
  .graphqlrc
Labels: maintenance

#812 fix: reloading an modifiable octo buffer may cause a runtime error
  lua/octo/init.lua
Labels: bug

#686 feat(notifications): show and read unread notifications
  README.md
  lua/octo/commands.lua
  lua/octo/config.lua
  lua/octo/pickers/fzf-lua/provider.lua
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/pickers/vim-clap/provider.lua
  lua/octo/utils.lua
Labels: enhancement

#816 fix: fzf-lua previwer (#784)
  lua/octo/pickers/fzf-lua/previewers.lua
Labels: bug

#818 Project without name
  lua/octo/ui/writers.lua
Labels: bug

#820 fix: use --slurp with --paginate to concat pages into valid json
  lua/octo/model/pull-request.lua
Labels: bug

#822 Fix fetch timeout for newly added files
  lua/octo/reviews/file-entry.lua
Labels: bug

#824 fix: detect pr branch with 'refs/pull/' branch config settings
  lua/octo/utils.lua
Labels: bug

#833 Fix gh pr checkout by added the SSH_AUTH_SOCK env variable
  lua/octo/gh/init.lua
Labels: bug
