Repository pwntester/octo.nvim, pull requests merged in 2025-07, with the labels that each got.

#1114 fix: write review decision when empty
  lua/octo/model/octo-buffer.lua
  lua/octo/ui/writers.lua
  lua/octo/utils.lua
Labels: bug, timelineItems

#1113 feat: add multiple reviewers/assignees at once
  lua/octo/commands.lua
  lua/octo/gh/init.lua
  lua/octo/gh/mutations.lua
  lua/octo/utils.lua
Labels: enhancement, command

#1111 fix: properly handle white space user cmd completion
  lua/octo/completion/init.lua
Labels: bug

#1126 fix: floating window content offset
  lua/octo/ui/window.lua
Labels: bug

#1121 feat: update DiffChange and DiffText to be more like GitHub
  lua/octo/constants.lua
  lua/octo/reviews/layout.lua
Labels: enhancement

#1124 feat(snacks): add `changed_files` picker
  lua/octo/config.lua
  lua/octo/pickers/snacks/provider.lua
Labels: enhancement, snacks

#1134 chore: fix stylua precommit step
  .pre-commit-config.yaml
  .stylua.toml
Labels: maintenance

#1130 Account for "NONE" status in `authorAssociation`
  lua/octo/ui/writers.lua
Labels: enhancement

#1135 chore: improve typing of OctoBuffer.node
  lua/octo/commands.lua
  lua/octo/config.lua
  lua/octo/gh/queries.lua
  lua/octo/init.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/navigation.lua
  lua/octo/pickers/fzf-lua/pickers/project_cards.lua
  lua/octo/pickers/fzf-lua/pickers/project_cards_v2.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/ui/writers.lua
  lua/octo/utils.lua
Labels: maintenance

#1139 fix: copy_sha error
  lua/octo/commands.lua
Labels: bug

#1131 [fix] Improve wording for merge queue commands on README
  README.md
  lua/octo/config.lua
Labels: maintenance

#1125 Add `Octo comment reply` and `<leader>cr` mapping
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/config.lua
  lua/octo/mappings.lua
Labels: enhancement

#1138 Type hint merge method
  lua/octo/config.lua
Labels: maintenance

#1119 feat(snacks): `commits` and `review_commits` picker
  lua/octo/config.lua
  lua/octo/pickers/snacks/provider.lua
Labels: snacks

#1143 fix: copy sha
  lua/octo/pickers/telescope/provider.lua
Labels: bug

#1109 fix(review)!: use merge base instead of current base head
  lua/octo/model/octo-buffer.lua
  lua/octo/model/pull-request.lua
  lua/octo/reviews/init.lua
  lua/octo/utils.lua
Labels: bug
