Repository pwntester/octo.nvim, pull requests merged in 2025-03, with the labels that each got.

#911 Add `:Octo pr runs` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/workflow_runs.lua
Labels: enhancement, command

#912 Expose current_buffer logic
  lua/octo/commands.lua
  lua/octo/completion.lua
  lua/octo/init.lua
  lua/octo/mappings.lua
  lua/octo/navigation.lua
  lua/octo/pickers/fzf-lua/pickers/assigned_labels.lua
  lua/octo/pickers/fzf-lua/pickers/assignees.lua
  lua/octo/pickers/fzf-lua/pickers/changed_files.lua
  lua/octo/pickers/fzf-lua/pickers/commits.lua
  lua/octo/pickers/fzf-lua/pickers/project_cards.lua
  lua/octo/pickers/fzf-lua/pickers/project_cards_v2.lua
  lua/octo/pickers/fzf-lua/pickers/project_columns.lua
  lua/octo/pickers/fzf-lua/pickers/project_columns_v2.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/reviews/init.lua
  lua/octo/ui/writers.lua
  lua/octo/utils.lua
Labels: maintenance

#913 Add colors to `Octo pr changes` and improve width
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/ui/colors.lua
Labels: enhancement, telescope

#907 Allow all notifications
  lua/octo/gh/init.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement

#908 break graphql into modules
  lua/octo/gh/graphql.lua
  lua/octo/gh/mutations.lua
  lua/octo/gh/queries.lua
  lua/octo/pickers/fzf-lua/pickers/project_columns_v2.lua
Labels: maintenance

#830 feat: add octo review browse to browse a pull request
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/reviews/init.lua
Labels: enhancement, command

#915 fix: set valid highlight for OctoFilePanelFileName
  README.md
  lua/octo/ui/colors.lua
  lua/octo/ui/writers.lua
Labels: bug

#927 refactor: switch remaining `vim.fn.json_...` calls to `vim.json`
  lua/octo/pickers/snacks/provider.lua
  lua/octo/reviews/init.lua
  lua/octo/workflow_runs.lua
Labels: maintenance

#929 Add `Octo comment url` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/gh/queries.lua
Labels: enhancement, command

#904 Refactor search logic
  lua/octo/gh/queries.lua
  lua/octo/pickers/fzf-lua/pickers/search.lua
  lua/octo/pickers/telescope/previewers.lua
  lua/octo/pickers/telescope/provider.lua
Labels: maintenance

#931 Add pinned and unpinned events to timeline
  lua/octo/gh/fragments.lua
  lua/octo/gh/mutations.lua
  lua/octo/gh/queries.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/ui/writers.lua
Labels: enhancement, timelineItems

#932 Add `:Octo issue pin` and `:Octo issue unpin`
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/gh/mutations.lua
Labels: enhancement, command

#936 Add subissues to timeline
  lua/octo/gh/fragments.lua
  lua/octo/gh/mutations.lua
  lua/octo/gh/queries.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/ui/writers.lua
Labels: enhancement, timelineItems

#937 Add parent issues to timeline
  lua/octo/gh/fragments.lua
  lua/octo/gh/mutations.lua
  lua/octo/gh/queries.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/ui/writers.lua
Labels: enhancement, timelineItems

#918 Add initial discussion buffer
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/config.lua
  lua/octo/gh/fragments.lua
  lua/octo/gh/mutations.lua
  lua/octo/gh/queries.lua
  lua/octo/init.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/pickers/telescope/previewers.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/ui/writers.lua
Labels: discussions

#940 Add helper to display all hightlight groups
  lua/octo/ui/colors.lua
Labels: maintenance

#941 Add the linked highlight groups to the helper as well
  lua/octo/ui/colors.lua
Labels: maintenance

#942 Remove extra space at end of "[DRAFT]"
  lua/octo/ui/writers.lua
Labels: maintenance

#944 920 add discussion to notifications
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/previewers.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/utils.lua
Labels: enhancement, discussions

#945 Add `:Octo discussion close` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/gh/mutations.lua
Labels: enhancement, command, discussions

#946 Add `:Octo discussion reopen` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/gh/mutations.lua
Labels: enhancement, command, discussions

#947 Add `:Octo discussion search` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/gh/queries.lua
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement, discussions

#950 949 octo discussion url does work
  lua/octo/commands.lua
  lua/octo/constants.lua
  lua/octo/utils.lua
  lua/tests/plenary/utils_spec.lua
Labels: bug, discussions

#952 Add `Octo parent add` and `Octo parent remove` commands
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/gh/fragments.lua
  lua/octo/gh/mutations.lua
  lua/octo/gh/queries.lua
Labels: enhancement, command

#955 Add `Octo parent edit` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
Labels: enhancement, command

#958 Add repo to Discussion buffer details section
  lua/octo/model/octo-buffer.lua
  lua/octo/pickers/telescope/previewers.lua
  lua/octo/ui/writers.lua
Labels: enhancement, discussions

#960 search completions
  lua/octo/completion/init.lua
  lua/octo/completion/search.lua
Labels: enhancement, command

#963 Add user and repo completion with repo: argLead
  lua/octo/completion/search.lua
  lua/octo/gh/queries.lua
Labels: enhancement, command

#965 add discussion state and number virtual text
  lua/octo/model/octo-buffer.lua
  lua/octo/pickers/telescope/previewers.lua
Labels: discussions

#966 Refactor completion and add additional search completions
  lua/octo/completion/search.lua
Labels: enhancement

#967 fix: add back fg
  lua/octo/ui/colors.lua
Labels: bug, setup

#972 Add discussion reply count to summary
  lua/octo/model/octo-buffer.lua
  lua/octo/pickers/telescope/previewers.lua
  lua/octo/ui/writers.lua
  lua/octo/utils.lua
Labels: discussions

#943 Add configuration option to use timeline icons
  README.md
  lua/octo/config.lua
  lua/octo/gh/fragments.lua
  lua/octo/ui/colors.lua
  lua/octo/ui/writers.lua
Labels: enhancement, timelineItems

#975 Adjust action location
  .github/workflows/labels.yml
Labels: maintenance

#994 move examples toward top
  README.md
Labels: documentation

#995 Use default labels for completions without repo
  lua/octo/completion/search.lua
Labels: enhancement, autocomplete

#976 Add commit header in timelineItems
  lua/octo/config.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/ui/writers.lua
Labels: UI, timelineItems

#997 Add discussion popup
  lua/octo/gh/queries.lua
  lua/octo/init.lua
  lua/octo/ui/writers.lua
Labels: enhancement, discussions

#998 consolidate copy url
  lua/octo/commands.lua
  lua/octo/pickers/fzf-lua/pickers/gists.lua
  lua/octo/pickers/fzf-lua/pickers/utils.lua
  lua/octo/pickers/snacks/provider.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/utils.lua
  lua/octo/workflow_runs.lua
Labels: maintenance

#1006 Use html_url for notification `<C-y>`
  lua/octo/pickers/telescope/provider.lua
Labels: bug

#964 Fix query used in fzf repo previewer
  lua/octo/pickers/fzf-lua/previewers.lua
Labels: bug, fzf

#985 Setup colors as init
  lua/octo/init.lua
Labels: bug

#1013 update CI/CD ubuntu version
  .github/workflows/tests.yml
Labels: maintenance

#1014 Safely get the user for the commit header
  lua/octo/ui/writers.lua
Labels: bug

#1000 feat: `gh run rerun|cancel`
  README.md
  lua/octo/config.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/workflow_runs.lua
Labels: enhancement
