Repository pwntester/octo.nvim, pull requests merged in 2025-05, with the labels that each got.

#1060 feat(snacks): enhance picker configuration and actions
  README.md
  lua/octo/config.lua
  lua/octo/pickers/snacks/provider.lua
  lua/tests/octo/config_spec.lua
Labels: enhancement

#1067 feat(snacks): improve format for issue list
  lua/octo/pickers/snacks/provider.lua
Labels: enhancement, snacks

#1065 feat: add command for marking notification as done
  README.md
  lua/octo/config.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement, telescope

#1077 Fix broken `:Octo review commit` command workflow
  lua/octo/model/octo-buffer.lua
  lua/octo/model/pull-request.lua
  lua/octo/reviews/file-entry.lua
  lua/octo/reviews/thread-panel.lua
Labels: bug

#1076 fix(colors): don't overwrite highlight groups if they exists
  lua/octo/ui/colors.lua
Labels: bug

#1080 Add `Octo discussion browser` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
  lua/octo/navigation.lua
Labels: enhancement, command, discussions

#1082 Remove unused imports
  lua/octo/discussions.lua
  lua/octo/mappings.lua
  lua/octo/navigation.lua
  lua/octo/pickers/fzf-lua/pickers/repos.lua
  lua/octo/workflow_runs.lua
Labels: maintenance

#1084 fix(env): add DBUS env var to enable accessing token in keyring
  lua/octo/gh/init.lua
Labels: bug, Enterprise compat
