Repository pwntester/octo.nvim, pull requests merged in 2025-04, with the labels that each got.

#893 Use correct binary for sync gh pr checkout
  lua/octo/reviews/init.lua
  lua/octo/utils.lua
Labels: maintenance

#1003 ProjectsV2 set and remove for telescope
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement, command, telescope

#1021 Support `Octo search is:repository <prompt>` and `Octo repo search <prompt>` functionality
  lua/octo/commands.lua
  lua/octo/completion/search.lua
  lua/octo/gh/queries.lua
  lua/octo/pickers/fzf-lua/pickers/repos.lua
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement, command, telescope

#1023 refactor file context
  lua/octo/gh/queries.lua
  lua/octo/utils.lua
Labels: maintenance

#1024 Changes colors.setup call from setup() to update_layout_for_current_file
  lua/octo/init.lua
Labels: bug

#1026 update pre-commit
  .pre-commit-config.yaml
Labels: maintenance

#1049 Add author association to PR details
  lua/octo/gh/queries.lua
  lua/octo/ui/writers.lua
Labels: UI

#1025 feat: implement `issue_templates` picker for snacks provider
  lua/octo/pickers/snacks/provider.lua
Labels: snacks

#1051 Provider snacks search
  lua/octo/gh/queries.lua
  lua/octo/pickers/snacks/provider.lua
Labels: snacks

#1054 Consolidate laugh emoji
  lua/octo/utils.lua
Labels: maintenance

#1055 fix(colors): use lua api to set highlights and initialize colors once (fix #1010)
  lua/octo/commands.lua
  lua/octo/init.lua
  lua/octo/ui/colors.lua
Labels: bug

#1057 fix(colors): `get_fg()` was getting `fg` but `ctermfg`
  lua/octo/ui/colors.lua
Labels: bug

#1050 Fix lost keymaps when switching tabs
  lua/octo/autocmds.lua
  lua/octo/reviews/init.lua
  lua/octo/reviews/layout.lua
Labels: bug
