Repository pwntester/octo.nvim, pull requests merged in 2025-02, with the labels that each got.

#840 feat: fix error when trying to open a review while it is already opened
  lua/octo/reviews/file-entry.lua
Labels: bug

#837 fix: Escape hyphen in ssh_aliases and check for nil in author.user
  lua/octo/ui/writers.lua
  lua/octo/utils.lua
  lua/tests/plenary/utils_spec.lua
Labels: bug

#827 fix: allow pr checkout from non-default repository
  lua/octo/reviews/init.lua
  lua/octo/utils.lua
Labels: bug

#845 fix: change renaming order swap
  lua/octo/commands.lua
  lua/octo/navigation.lua
  lua/octo/pickers/telescope/entry_maker.lua
Labels: bug

#846 fix: handle reference timeline event without actor
  lua/octo/ui/writers.lua
Labels: bug

#847 Include mode of command in config and make submit window commands work in insert mode
  README.md
  lua/octo/config.lua
  lua/octo/utils.lua
Labels: Reviews

#851 Improve buffer behavior after thread creation
  lua/octo/autocmds.lua
  lua/octo/commands.lua
  lua/octo/mappings.lua
  lua/octo/model/octo-buffer.lua
  lua/octo/reviews/file-entry.lua
  lua/octo/reviews/init.lua
  lua/octo/reviews/thread-panel.lua
  lua/octo/reviews/thread.lua
Labels: Reviews

#849 Feat: repo specific notifications
  README.md
  lua/octo/config.lua
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement

#853 Pass repo to notification picker
  lua/octo/commands.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement

#858 feat: add snacks picker support for issues, prs, and notifications
  README.md
  lua/octo/config.lua
  lua/octo/pickers/snacks/provider.lua
Labels: enhancement

#859 test for nvim v0.10.0 in action
  .github/workflows/tests.yml
Labels: maintenance

#860 fix(fzf): upstream change "" to nil when no selected
  lua/octo/pickers/fzf-lua/previewers.lua
Labels: fzf, maintenance

#863 add a callback helper function
  lua/octo/gh/init.lua
Labels: maintenance

#864 feat(completion): Add blink-cmp-git for blink.cmp
  README.md
  doc/octo.txt
Labels: documentation

#865 allow for arbitrary callback in label pickers
  lua/octo/commands.lua
  lua/octo/pickers/fzf-lua/pickers/assigned_labels.lua
  lua/octo/pickers/fzf-lua/pickers/labels.lua
  lua/octo/pickers/telescope/provider.lua
Labels: enhancement

#866 Create label from repo
  lua/octo/commands.lua
Labels: enhancement

#867 Add `:Octo label delete` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
Labels: enhancement

#869 feat(docs): add snacks.nvim to installation section
  README.md
Labels: documentation

#871 Refactor milestone logic
  lua/octo/gh/init.lua
  lua/octo/utils.lua
  lua/tests/plenary/gh_spec.lua
Labels: maintenance

#872 add REST API functions and metatable for get
  lua/octo/gh/init.lua
Labels: enhancement

#873 Use info only on pr ready command success
  lua/octo/commands.lua
Labels: maintenance

#879 Add typing to gh.run
  lua/octo/gh/init.lua
Labels: maintenance

#880 Migrate gh pr checks logic
  lua/octo/commands.lua
Labels: maintenance

#882 Use jq and callback in state change
  lua/octo/commands.lua
Labels: maintenance

#883 Create milestone via post API
  lua/octo/utils.lua
Labels: maintenance

#884 allow for gh run commands as well as previous run function
  lua/octo/gh/init.lua
Labels: enhancement, command

#885 Favor gh.api.graphql and deprecate gh.graphql
  lua/octo/gh/init.lua
  lua/octo/pickers/telescope/provider.lua
Labels: maintenance

#638 feat: poc octo run list
  README.md
  lua/octo/commands.lua
  lua/octo/config.lua
  lua/octo/constants.lua
  lua/octo/navigation.lua
  lua/octo/pickers/fzf-lua/provider.lua
  lua/octo/pickers/snacks/provider.lua
  lua/octo/pickers/telescope/entry_maker.lua
  lua/octo/pickers/telescope/previewers.lua
  lua/octo/pickers/telescope/provider.lua
  lua/octo/pickers/vim-clap/provider.lua
  lua/octo/workflow_runs.lua
Labels: enhancement

#887 Refactor various utils queries to use jq
  lua/octo/gh/graphql.lua
  lua/octo/utils.lua
Labels: maintenance

#888 Pass table to format templated endpoint
  lua/octo/gh/init.lua
  lua/tests/plenary/gh_spec.lua
Labels: maintenance

#895 refactor issue navigation
  lua/octo/gh/graphql.lua
  lua/octo/navigation.lua
Labels: maintenance

#898 fix: disable cursorline due to Neovim bug
  lua/octo/reviews/file-entry.lua
Labels: bug

#897 Add `:Octo comment suggest` command
  README.md
  doc/octo.txt
  lua/octo/commands.lua
Labels: enhancement

#901 802 error on large number of discussions
  lua/octo/pickers/telescope/provider.lua
  lua/octo/utils.lua
  lua/tests/plenary/utils_spec.lua
Labels: bug, discussions

#902 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: maintenance

#906 Repo Buffer not rendering and repo list not passing correct filename
  lua/octo/init.lua
  lua/octo/pickers/telescope/entry_maker.lua
Labels: bug
