Repository pwntester/octo.nvim, pull requests merged in 2025-09, with the labels that each got.

#1168 docs: add aside concerning ssh aliases when getting unauthenticated errors
  README.md
Labels: documentation

#1170 fix: review commits mapping not providing callback
  lua/octo/mappings.lua
Labels: bug

#1167 fix(pr): do not show OPEN status when in DRAFT state
  lua/octo/ui/writers.lua
Labels: UI

#1173 fix: add missing fragments
  lua/octo/gh/mutations.lua
Labels: bug
